name: koyevi
description: koyevi

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+11

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  pin_code_fields: ^7.4.0
  cupertino_icons: ^1.0.2
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.4
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.1+1
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  shared_preferences: ^2.0.15
  easy_localization: ^3.0.1
  easy_localization_generator: ^0.0.3
  uni_links: ^0.5.1
  dio: ^4.0.6
  flutter_rating_bar: ^4.0.1
  animated_text_kit: ^4.2.2
  dynamic_height_grid_view: ^0.0.3
  google_maps_flutter: ^2.2.0
  permission_handler: ^10.0.0
  geolocator: ^9.0.1
  fluttertoast: ^8.0.9
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.8
  flutter_easyloading: ^3.0.5
  flutter_gif: ^0.0.4
  flutter_pin_code_fields: ^1.2.0
  auto_size_text: ^3.0.0
  app_tracking_transparency: ^2.0.3
  device_info_plus: ^8.0.0
  launch_review: ^3.0.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/gif/
    - assets/icons/svg/
    - assets/icons/png/
    - assets/lang/
    - assets/theme/
